import { Footer, Header, DonateButton } from "../components";
export const metadata={title:"Our Work",description:"Explore Goodwill Alliance's areas of focus, including seniors and veterans, food and essentials, community programs, partnerships, children and families, and special assistance."};
const focusAreas=[
{number:"01",title:"Seniors & Veterans",text:"We are developing ways to support seniors and veterans facing hardship, isolation, financial challenges, or unmet practical needs through assistance and community-based initiatives."},
{number:"02",title:"Food & Essential Needs",text:"We aim to help people and families facing hardship access food, essential goods, and other practical resources as programs and funding become available."},
{number:"03",title:"Community Programs",text:"We plan to organize programs and community initiatives that respond to real needs and bring people and resources together."},
{number:"04",title:"Nonprofit & Community Partnerships",text:"We seek opportunities to collaborate with community organizations and other nonprofits so that resources, experience, and support can reach more people."},
{number:"05",title:"Children & Families",text:"Our broader mission includes helping children and families experiencing hardship through appropriate community programs, essential assistance, and partnerships."},
{number:"06",title:"Emergency & Special Assistance",text:"When circumstances and resources allow, Goodwill Alliance may respond to urgent or special needs affecting people and communities, including needs beyond our immediate area."}
];
export default function OurWorkPage(){return <main><Header /><section className="page-hero"><div className="container narrow"><p className="eyebrow">OUR WORK</p><h1>Flexible enough to respond. Focused enough to make a difference.</h1><p className="lead">Goodwill Alliance is expanding its programs and partnerships around areas where practical assistance and community support can help people facing hardship.</p></div></section>
<section className="section soft"><div className="container work-list">{focusAreas.map(a=><article className="work-row" key={a.title}><div className="work-number">{a.number}</div><div><h2>{a.title}</h2><p className="body-large">{a.text}</p></div></article>)}</div></section>
<section className="section"><div className="container content-grid"><div><p className="eyebrow">RESPONSIBLE GROWTH</p><h2>Programs will grow with resources and community needs.</h2></div><div className="prose"><p>Goodwill Alliance is building the capacity for specific initiatives and measurable community impact. We will add details about active programs, eligibility, partnerships, and results as those efforts are established.</p><p>We do not want to promise services that are not yet available. Our goal is to grow responsibly, communicate clearly, and direct resources where they can provide meaningful help.</p><DonateButton children="Support Our Work" /></div></div></section><section className="section soft"><div className="container"><p className="eyebrow">PAST COMMUNITY EFFORTS</p><h2>Supporting Ukrainian Refugees in Austria</h2><div className="prose"><p>During the early stages of the war in Ukraine, Goodwill Alliance provided financial support to an organization in Austria assisting Ukrainian refugees. The funding helped support operating expenses as the organization provided assistance to people displaced by the conflict.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(280px, 1fr))",gap:"20px",marginTop:"28px"}}><img src="/a2099abe-710d-4a58-8c38-9e6a95916710.jpeg" alt="Volunteers preparing food in Austria" style={{width:"100%",height:"auto",borderRadius:"12px"}} /><img src="/986bacb7-2272-4e14-b854-1cb2a85a3841.jpeg" alt="Food supplies for refugee assistance in Austria" style={{width:"100%",height:"auto",borderRadius:"12px"}} /></div></div></section><Footer /></main>}
